apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod1
    my-label: test
  name: pod1
spec:
  containers:
  - image: bash
    name: pod1
    args:
    - "bash"
    - "-c"
    - "hostname >> hostname && sleep 1d"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}